from django.urls import path
from .views import (
    dashboard,
     RegistrationView,
    UsernameValidation,
    EmailValidation,
    VerificationView,
    LoginView,
    LogoutView,
    RequestPasswordResetEmail,
    CompletPasswordReset,
    index,
    add_expenses,
    expense_edit,
    expense_delete,
    search_expenses,
    expense_income_summary,
    stats_view,
    userindex,
    incomeindex,
    add_income,
    edit_income,
    income_delete,
    search_income,
    generate_report
    )
from django.views.decorators.csrf import csrf_exempt


urlpatterns = [
    path('', dashboard, name= "dashboard"),
    path('generate_report', generate_report, name = "generate_report"),
    path('userindex/', userindex, name = "preferences"),
    path('register/',RegistrationView.as_view(),name = "register"),
    path('user-validation/', csrf_exempt(UsernameValidation.as_view()), name= "user-validation"),
    path('email-validation/', csrf_exempt(EmailValidation.as_view()), name= "email-validation"),
    path('login/', LoginView.as_view(), name= "login"),
    path('logout/',LogoutView.as_view(), name = "logout"),
    path('activate/<uidb64>/<token>',VerificationView.as_view(),name="activate"),
    path('set_new_password/<uidb64>/<token>',CompletPasswordReset.as_view(),name="reset_user_password"),
    path('request-reset-link',RequestPasswordResetEmail.as_view(), name="request_password" ),
    path('expenses/',index,name =  "expenses" ),
    path('add_expenses', add_expenses, name= "add_expenses"),
    path('expense_edit/<int:id>',expense_edit,name="expense_edit"),
    path('expense-delete/<int:id>',expense_delete, name = "expense-delete"),
    path('search-expense',csrf_exempt(search_expenses), name="search_expenses"),
    path('expenses-incomes-summary/', expense_income_summary, name='expenses_incomes_summary'),
    path('stats/', stats_view, name="stats"), 
     path('incomeindex', incomeindex, name= "income"),
    path('add_income', add_income, name = "add_income"),
    path('edit_income/<int:id>', edit_income, name = "edit_income"),
    path('delete_income/<int:id>', income_delete, name= "delete_income"),
    path('search_income', csrf_exempt(search_income), name = "search_income"),
]